name       : xfce4-appfinder
version    : 4.18.0
release    : 1
source     :
    - https://archive.xfce.org/src/xfce/xfce4-appfinder/4.18/xfce4-appfinder-4.18.0.tar.bz2 : 962a98d7b327d2073ed4cd0f78bce7945ed51b97d52fd60196e8b02ef819c18c
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Application launcher and finder.
description: |
    Application launcher and finder.
builddeps  :
    - pkgconfig(garcon-gtk3-1)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libxfconf-0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
